#!/bin/bash
# WF 2020-02-13
export PYTHONPATH="."
os=$(uname -a)
python="python3"
which $python
if [ $? -ne 0 ]
then
  echo $python is missing 1>&2
  exit 1
fi
app="dgs/webserver.py"
case $os in
  Darwin*) ;;
esac
echo "running on $os"
nohup $python $app&
sleep 4
open http://localhost:5003
tail -f nohup.out
