#!/bin/bash
# WF 2020-02-13
autoinstall() {
  local l_cmd="$1"
  local l_package="$1"
  which $l_cmd>/dev/null
  if [ $? -ne 0 ]
  then
    echo "$l_cmd is not installed" 1>&2
    echo "auto-installing it"
    inst="sudo apt-get install"
    os=$(uname -a)
    case $os in
      Darwin*) inst="sudo port install"
    esac
    $inst $l_package
  fi
}
autoinstall dot graphviz
autoinstall mscgen mscgen
autoinstall java openjdk-8-jdk
if [ ! -f plantuml.jar ]
then
  echo "downloading plantuml"
  curl -L http://sourceforge.net/projects/plantuml/files/plantuml.jar/download -o plantuml.jar
fi
pip install . 
